apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 7.3.9
    helm:
      valueFiles:
      - $repo-values/monitoring/grafana/argocd-files/values.yaml
  - repoURL: 'https://github.com/fruetalo182/platform-stack.git'
    targetRevision: HEAD
    ref: repo-values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true