---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-ini
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-ini
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: grafana-ini-prod

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-datasources-creds-prod
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-datasources-creds-prod
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: grafana-datasources-creds-prod