apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fruetalo182/platform-stack.git
    targetRevision: HEAD
    path: opencost/argocd-files
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  syncPolicy:
    syncOptions:
    - CreateNamespace=true