apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dns-provider-api-token
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: dns-provider-api-token
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: DNS_PROVIDER_API_TOKEN