---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-prod
  namespace: n8n-prod
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: n8n-prod
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: n8n-prod