apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prome-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prom-stack
    targetRevision: 58.1.3
    helm:
      valueFiles:
      - $repo-values/monitoring/kube-prom-stack/argocd-files/values.yaml  
  - repoURL: 'https://github.com/fruetalo182/platform-stack.git'
    targetRevision: HEAD
    ref: repo-values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true