alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: "400Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: 1
    enableRemoteWriteReceiver: true
    additionalScrapeConfigs: |
      - job_name: opencost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
        - names:
          - opencost.opencost
          type: 'A'
          port: 9003
      - job_name: loki
        honor_labels: true
        scrape_interval: 30s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
        - names:
          - loki-gateway.monitoring
          type: 'A'
          port: 80

prometheus-node-exporter:
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "200m"

kube-state-metrics:
  metricLabelsAllowlist:
  - deployments=[owner, team, repo]
  - pods=[app, owner, team, env, repo]

grafana:
  enabled: false